"""initial_schema

Revision ID: b3e9e2389f20
Revises: 
Create Date: 2026-04-10 02:00:03.183739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e9e2389f20'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create ENUM types idempotently (may already exist if tables were dropped
    # without dropping types in PostgreSQL)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE role AS ENUM ('admin', 'operador', 'viewer');
        EXCEPTION
            WHEN duplicate_object THEN NULL;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE quotestatus AS ENUM ('draft', 'confirmed', 'invoiced', 'cancelled');
        EXCEPTION
            WHEN duplicate_object THEN NULL;
        END $$;
    """)

    op.create_table('config_params',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_params_key'), 'config_params', ['key'], unique=True)
    op.create_table('models',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_brand'), 'models', ['brand'], unique=False)
    op.create_index(op.f('ix_models_name'), 'models', ['name'], unique=False)
    op.create_table('services',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_category'), 'services', ['category'], unique=False)
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=False)
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('warranty_days', sa.Integer(), nullable=False),
    sa.Column('return_policy', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'operador', 'viewer', name='role', create_type=False), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('config_history',
    sa.Column('config_id', sa.String(length=36), nullable=False),
    sa.Column('old_value', sa.String(length=255), nullable=True),
    sa.Column('new_value', sa.String(length=255), nullable=False),
    sa.Column('changed_by', sa.String(length=255), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['config_params.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_history_config_id'), 'config_history', ['config_id'], unique=False)
    op.create_table('quotes',
    sa.Column('quote_number', sa.String(length=20), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('draft', 'confirmed', 'invoiced', 'cancelled', name='quotestatus', create_type=False), nullable=False),
    sa.Column('technician_cost_hr', sa.Float(), nullable=False),
    sa.Column('target_margin', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_model_id'), 'quotes', ['model_id'], unique=False)
    op.create_index(op.f('ix_quotes_quote_number'), 'quotes', ['quote_number'], unique=True)
    op.create_index(op.f('ix_quotes_status'), 'quotes', ['status'], unique=False)
    op.create_table('service_catalog',
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('bjx_labor_cost', sa.Float(), nullable=True),
    sa.Column('bjx_parts_cost', sa.Float(), nullable=True),
    sa.Column('duration_hrs', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'service_id', 'is_current', name='uq_catalog_model_service_current')
    )
    op.create_index(op.f('ix_service_catalog_is_current'), 'service_catalog', ['is_current'], unique=False)
    op.create_index(op.f('ix_service_catalog_model_id'), 'service_catalog', ['model_id'], unique=False)
    op.create_index(op.f('ix_service_catalog_service_id'), 'service_catalog', ['service_id'], unique=False)
    op.create_table('supplier_prices',
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('ref_cost', sa.Float(), nullable=False),
    sa.Column('labor_cost', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_prices_is_current'), 'supplier_prices', ['is_current'], unique=False)
    op.create_index(op.f('ix_supplier_prices_model_id'), 'supplier_prices', ['model_id'], unique=False)
    op.create_index(op.f('ix_supplier_prices_service_id'), 'supplier_prices', ['service_id'], unique=False)
    op.create_index(op.f('ix_supplier_prices_supplier_id'), 'supplier_prices', ['supplier_id'], unique=False)
    op.create_table('quote_lines',
    sa.Column('quote_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=True),
    sa.Column('duration_hrs', sa.Float(), nullable=False),
    sa.Column('labor_cost', sa.Float(), nullable=False),
    sa.Column('parts_cost', sa.Float(), nullable=False),
    sa.Column('total_bjx_cost', sa.Float(), nullable=False),
    sa.Column('brame_price', sa.Float(), nullable=False),
    sa.Column('margin_pesos', sa.Float(), nullable=False),
    sa.Column('margin_pct', sa.Float(), nullable=False),
    sa.Column('suggested_price', sa.Float(), nullable=False),
    sa.Column('gap_vs_target', sa.Float(), nullable=False),
    sa.Column('margin_status', sa.String(length=20), nullable=False),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_lines_quote_id'), 'quote_lines', ['quote_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_lines_quote_id'), table_name='quote_lines')
    op.drop_table('quote_lines')
    op.drop_index(op.f('ix_supplier_prices_supplier_id'), table_name='supplier_prices')
    op.drop_index(op.f('ix_supplier_prices_service_id'), table_name='supplier_prices')
    op.drop_index(op.f('ix_supplier_prices_model_id'), table_name='supplier_prices')
    op.drop_index(op.f('ix_supplier_prices_is_current'), table_name='supplier_prices')
    op.drop_table('supplier_prices')
    op.drop_index(op.f('ix_service_catalog_service_id'), table_name='service_catalog')
    op.drop_index(op.f('ix_service_catalog_model_id'), table_name='service_catalog')
    op.drop_index(op.f('ix_service_catalog_is_current'), table_name='service_catalog')
    op.drop_table('service_catalog')
    op.drop_index(op.f('ix_quotes_status'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_quote_number'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_model_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_config_history_config_id'), table_name='config_history')
    op.drop_table('config_history')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_index(op.f('ix_services_category'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_models_name'), table_name='models')
    op.drop_index(op.f('ix_models_brand'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_config_params_key'), table_name='config_params')
    op.drop_table('config_params')
    # ### end Alembic commands ###
